create table Student(
Regno int primary key,
Studname varchar(50),
dept varchar(20)
);

create table Fees(
Regno int primary key,
AmountPaid Decimal(10,2)
);

insert into Student values(101,'Gagan B K','CSE'),
(102,'Ajith','CSE'),
(103,'Sumanth','ECE'),
(104,'Dayan','ME')

insert into Fees values (101,50000.00),
(102,55000.00),
(105,30000.00);

select S.Regno,S.studname,S.dept,F.amountpaid from Student S inner join Fees F on 
S.Regno=F.Regno

--Join - Left outer Join 
select S.Regno,S.studname,S.dept,F.amountpaid from Student S left outer join Fees F on 
S.Regno=F.Regno

--Join - Right outer Join  
select S.Regno,S.studname,S.dept,F.Regno,F.amountpaid 
from Student S right join Fees F on 
S.Regno=F.Regno

--Join - Full Outer Join
select S.Regno,S.studname,S.dept,F.Regno,F.amountpaid from Student S full outer join Fees F 
on S.Regno=F.Regno

--cross join
select * from Student S cross join Fees F 


create table Employee(
Empid int primary key,
Empname varchar(50),
Deptid int,
Managerid int
);

create table Department(
Did int primary key,
Dname varchar(50)
);

insert into Employee values (1,'Gagan',101,1),
(2,'Ajith',102,null),
(3,'Dayan',101,1),
(4,'Sumanth',103,2);

insert into Department values(101,'Software'),
(102,'Core'),
(103,'Finance');

select * from Employee;
select * from Department

--inner join
select E.empname,E.deptid,D.dname from Employee E join Department D on E.deptid=D.did

--left join
select E.empname,E.deptid,D.dname 
from Employee E 
left join Department D on E.deptid=D.did

--right join
select E.empname,E.deptid,D.dname 
from Employee E 
right join Department D on E.deptid=D.did

--full join
select E.empname,E.deptid,D.did,D.dname 
from Employee E full join Department D on 
E.deptid=D.did

--self join - Find the match with same table

select E1.Empid,E1.Empname from Employee E1 
join Employee E2 on E1.empid=E2.Managerid

--PL/SQL - Stored procedure using functions – plpgsql – with parameter and returning integer
create or replace function countempl(department varchar(15))
returns int
language plpgsql
as
$$
 declare
 countemp int;
 begin
 select count(*) into countemp from student where dept = department;
 return countemp;
 end;
$$

select countempl('CSE')

--PL/SQL - Stored procedure using functions – plpgsql – with parameter and returning int
create or replace function countemp(department int)
returns int
language plpgsql
as
$$
 declare
 countemp int;
 begin
 select count(*) into countemp from employee 
 where deptid = department;
 return countemp;
 end;
$$

select countemp(101)

--PL/SQL - Stored procedure using functions – plpgsql – with parameter and returning text
create or replace function getempname(eid int)
returns text
language plpgsql
as
$$
 declare
 resultname text;
 begin
 select empname into resultname from employee where empid = eid;
 return resultname;
 end;
$$
select getempname(2)


create or replace function getempdetails(did int)
returns table(empname varchar(35),salary integer)
as
$$
 begin
 return query select E.empname,E.salary from employee E where deptid = did; 
 end;
$$
language plpgsql;
select getempdetails(102)

--Views
create table Students(Sid int primary key generated by default as identity,
Sname varchar(25),Scity varchar(30),Dept varchar(15),
Feespaid boolean,Paidon date,Placed boolean,
Placedon date,Conduct varchar(20))

insert into Students(Sname,Scity,Dept,Feespaid,Paidon,Placed,PLacedon,Conduct) 
values('Srika','Chennai','CSE','yes','2023/09/2','yes','2023/8/25','Good'),
('Neha','Hyderabad','ECE','yes','2023/10/13','yes','2023/8/25','Good'),
('Rahul','Mumbai','ECE','yes','2023/06/15','yes','2023/8/25','Good'),
('Naman','Hyderabad','EEE','yes','2023/07/22','yes','2023/8/25','Good'),
('Lithesh','Bangalore','MECH','yes','2023/07/20','yes','2023/8/25','Good'),
('Mano','Mumbai','MECH','yes','2023/08/20','yes','2023/8/25','Good'),
('Sruthi','Bangalore','CSE','yes','2023/08/25','yes','2023/8/25','Good'),
('Suman','Chennai','IT','yes','2023/07/20','yes','2023/8/25','Good')

select * from Students

insert into Students 
values(14,'Mahisree','Hyderabad','ECE','yes','2023/11/13','yes','2023/8/25','Good')

create or replace view StudFees as
select Sid,Sname,Dept,Feespaid,Paidon
from Students
select * from StudFees
select * from Students
insert into StudFees values(15,'Cherishma','CSE','yes','2023/6/12','Good')


